server:
  port: 8761

eureka:
  client:
    registerWithEureka: false #tells the built-in eureka client to not register itself with eureka, because we should act as a server
    fetchRegistry: false
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 10000
